# -*- coding: utf-8 -*-
"""Code Club Session 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/warwickdatascience/beginners-python/blob/master/session_two/session_two_blank_template.ipynb

<a href="https://colab.research.google.com/github/warwickdatascience/beginners-python/blob/master/session_two/session_two_blank_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>Spotted a mistake? Report it <a href="https://github.com/warwickdatascience/beginners-python/issues/new">here</a></center>

# Beginner's Python—Session Two Template

## User Input

### Introduction

Use the input function to ask the user a question and print the response
"""

colour = input("What is your favourite colour? ")
print ("I love", colour ,"too")

Ask for numeric user input and assign this to a variable. Check this variables type and then convert it to an integer. Check the type again, perform some maths on the variable, and print the result

question = int (input( "How many cats do you own? "))
print(type (question))
print("You have", question, "cool!")

"""### Standard Puzzles

Remake the farm yard animal puzzle from session one using user input
"""

numcows = int (input("How many cow are there? "))
numchickens = int (input("How many chickens are there? "))
numpigs = int (input("How many pigs are there? "))

print("There are", numcows*4 +
      numchickens*2+ 
      numpigs*4, "legs on the farm." )



"""### Bonus Puzzles

Try adding `\r\n` to the end of your question in `input()`
"""

question = input("What is your favourite colour? \r\n")

"""## Variables Types

### Introduction

Add two strings together to concatenate their contents
"""

example = print( "test1"+ "test2")

"""Multiply a string by an integer"""

example2 = print ("test1"*2)

"""Try to multiply a string by a whole number stored as a float type to confirm that you recieve an error"""

x= float (5)
print(type(x))
example3 = print("test1"*x)

"""Above indicates the error

### Standard Puzzles

What could go wrong with the presentation code?

*   Your line could be too long

*   There could be an indent 

*   You could overlap a value

*   You could multiple a str by a float

## Summation

### Introduction

Create a list of numbers
"""

num = [2,4,6,8]

"""Calculate the sum of these numbers and store this as a variable, then print this value"""

print (sum(num))

"""### Standard Puzzles

Create a list with the values 193, 452, 67, 891, and 10
"""

number = [193,452,67,891,10]

"""Find the sum of the items in the list and store it as a variable"""

total =sum(number)

"""Use this variable to print the sum as part of a meaningful statement"""

print("The total of your numbers was", total)

"""### Bonus Puzzles

Confirm that lists can contain negative and decimal numbers and that `sum()` behaves as you would expect with these
"""

test = [-3, 1.7,4,9.8]
proof = -3 + 1.7 +4 + 9.8
exm = sum(test)
print("The sum expected is", exm , "this is the same as", proof)

"""## Min & Max

### Introduction

Create a list of numbers
"""

num = [-1,2,3,4,5]

"""Calculate the minimum of this list and print it in a meaningful statement"""

small = min(num)
print("The minimum value on the list is", small)

"""Repeat this for the maximum"""

large = max(num)
print( "The maximum value on the list is", large)

"""### Standard Puzzles

Create a list of numbers and find the minimum and maximum
"""

digits = [34,56,2,100,9]
small = min(digits)
large = max(digits)
print("The miminium and maximum value is", 
      small, "&", large, "respectively.")

"""Use these to find the range of the data and print this in a meaningful statement"""

spread = (large - small )
print("The range of the list is", spread)

"""## Length

### Introduction

Create a list of numbers and print the number of items it contains
"""

practise = [3,5,6,2,8]
print("The numbers contined in the list are", len(practise))

"""Create a string and print out the number of characters it contains"""

colours = "blue"
print("The number of characters are", len(colours))

"""### Standard Puzzles

Ask the user for a string input
"""

word = input("Hey can you type in a random word?")
print(word, "is a good choice!")

"""Output the length of this string"""

num = len(word)
print("There are", 
      num, "letters","in", word)

"""### Bonus Puzzles

Use the supplied code to let the user input the values of a list
"""

See example

"""Print the length of this list"""

See example