# -*- coding: utf-8 -*-
"""Code Club Session 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/warwickdatascience/beginners-python/blob/master/session_five/session_five_blank_template.ipynb

<a href="https://colab.research.google.com/github/warwickdatascience/beginners-python/blob/master/session_five/session_five_blank_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>Spotted a mistake? Report it <a href="https://github.com/warwickdatascience/beginners-python/issues/new">here</a></center>

# Beginner's Python—Session Five Template

## Looping Through a Range

### Introduction

Use a for loop to print the numbers zero to four
"""

counter_variable = [1,2,3,4,5,6,7,8,9,10]

Use a for loop to print the numbers two to five

for counter_variable in range(5):
  print(counter_variable)

"""We can do the same thing for a while loop but it is longer"""

counter = 0
while counter < 5:
  print(counter)
  counter += 1

"""### Standard Puzzles

Use a for loop to print the number -5 to 5, inclusive
"""

for counter in range(-5,6):
  print(counter)

"""Print the first ten square numbers"""

for num in range(1,11):
  print(num**2)

"""### Bonus Puzzles

Experiment with passing a third argument into `range(...)`. What does it do?
"""

for nums in range(1,11,2):
  print(nums)

"""It prints out the numbers from 1 to 11 in twos

Use this technique to count down from ten to zero
"""

for counts in range(10,0,-1):
  print(counts)

"""## Looping Through a List

### Introduction

Create a shopping list and print out each item in a sentence
"""

shopping_list = [ "bread", 
                 "eggs", "apples"]
for item in shopping_list:
  print( "Remember to buy", item)

"""### Standard Puzzles

Calculate the product of the elements in a list (see the presentation for a similar example)
"""

numbers = [2,4,2,5]
running_product = 1
for i in numbers:
  running_product = running_product*i
print("The product of elements is", running_product)

"""Use a for loop to count how many positive elements a numeric list contains"""

number = [-1,3,-7,4]
counter = 0
for item in number:
  if item > 0:
    counter += 1
print("There are", counter, "positive elements")

"""## Early-stopping

### Introduction

Print the elements of a list until a negative number is encountered, at which point you should stop
"""

my_list = [4,3,0,2,-1,4]
for count in my_list:
  if count == 0:
    print("Error! Its zero.")
    continue
  if count < 0:
    print("Oh no! You got a negative number.")
    break
  print(count)

"""Print the elements of a list, skipping any negative values"""

my_list = [4,3,1,2,-1,4]
for count in my_list:
  if count < 0:
    continue
  print(count)

"""## Enumeration

### Introduction

Use enumeration to print out the elements of a list alongside their ordinal indices
"""

calander = ['meeting', 'break',
            'research', 'lunch']
print("What is on today:")
for index, item in enumerate(calander):
  print(str(index+1)+ '.', item)

"""### Standard Puzzles

Define the list shown in the presentation
"""

list_of_numbers = [1,-2,2,5]

"""Print whether each element is greater than, equal to, or less than its index"""

for index, numbers in enumerate(list_of_numbers):
  if index > numbers:
   print("Element is greater than the corresponding index ")
  elif index == numbers:
    print("Element is equal to index")
  else:
    print("Index is less than element ")

"""Use enumeration to print every other element of a list"""

list_of_numbers = [5,3,2,1]
for i,n in enumerate(list_of_numbers):
  if i % 2 == 0:
    print(n)