# -*- coding: utf-8 -*-
"""Code Club Session 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/warwickdatascience/beginners-python/blob/master/session_seven/session_seven_blank_template.ipynb

<a href="https://colab.research.google.com/github/warwickdatascience/beginners-python/blob/master/session_seven/session_seven_blank_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>Spotted a mistake? Report it <a href="https://github.com/warwickdatascience/beginners-python/issues/new">here</a></center>

# Beginner's Python—Session Seven Template

## Dictionaries

### Introduction

Create a dictionary containing an integer, a string, and a list
"""

zoo = {'num_of_animals':30,
       'type_of_animals': 'tigers',
       'tigers': ['bengal', 'siberian']
}

Access one of the values from this dictionary

zoo['type_of_animals']

"""Try to access a non-existant key to confirm you recieve an error"""

zoo['lions']

"""Use the `in` keyword to safely access a dictionary key that may not exist"""

if 'lions' in zoo:
  print(zoo['lions'])
else:
  print('Of course, there are lions in the zoo!')

"""### Standard Puzzles

Create a dictionary with some information about you and print a few of the values
"""

about_me = {'name': 'mabel',
            'age': 20,
            'height': ['5ft8', '173cm']
            }

about_me['name']

"""What do you think the code in the presentation will do? Try it

It will print the last given value of x
"""

my_dict ={'x': 1, 'y': 2, 'x':3}
print(my_dict['x'])

"""### Bonus Puzzles

Experiment with using the `.get()` method of dictionaries. What are the advantages of using this?
"""

about_me.get('name')

"""## Manipulating Dictionaries

### Introduction

Add a new item to a dictionary
"""

about_me['eye colour'] ='brown'
print(about_me)

"""Overwrite the value of a dictionary item"""

about_me['height'] = 173.5
print(about_me)

"""Delete an item from a dictionary using its key"""

del about_me['age']
print(about_me)

"""### Standard Puzzles

Create the dictionary as defined in the presentation and manipulate it as described
"""

num= {'one': 1, 'two': 2,'three': 4 }
num['three']=3
num['four']=4
print(num)

"""Create an empty dictionary called `square`"""

square = {}

"""Fill this dictionary with key-value pairs for the squares of the integers -5 to 5"""

for n in range(-5,6):
  square[n] = n ** 2
print(square)

"""### Bonus Puzzles

Create a nested dictionary and access a value from an inner dictionary
"""

employees = {
    'employee1': {'manager': 'chris', 
                  'jobtitle': 'sales assisant'
                  },
    'employee2': {
        'manager':'meg',
        'jobtitle' :'cleaner'
    }
}

print(employees['employee1']['manager'])

"""## Looping Through Dictionaries

### Introduction

Create a simple dictionary to practise looping through
"""

ages = {'Chris': 20, 'Meg': 23}

"""Loop through a dictionary by key"""

for name in ages.keys():
    print(name)

"""Loop through a dictionary by value"""

for age in ages.values():
    print(age)

"""Loop through a dictionary be item"""

for name, age in ages.items():
    print(name, "is", age)

"""### Standard Puzzles

Create a function that can count the occurances of words in a list and print these in a readable fashion
"""

def count_string(shopping_list):
  counts = {}


  for i in shopping_list:
    if i in counts:
      counts[i] += 1
    else:
      counts[i]=1

  for i, j in counts.items():
    print("There are", i ,"occrences of", j)

count_string(['ham', 'ham', 'cheese', 'spam'])