# -*- coding: utf-8 -*-
"""session_four_exercises.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/warwickdatascience/beginners-python/blob/master/session_four/session_four_exercises.ipynb

<a href="https://colab.research.google.com/github/warwickdatascience/beginners-python/blob/master/session_four/session_four_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>Spotted a mistake? Report it <a href="https://github.com/warwickdatascience/beginners-python/issues/new">here</a></center>

# Beginner's Python—Session Four Homework Exercises

## Non-numeric Lists

Ask the user to input 3 days of the week (using `input()` three times) and use these to create a list of strings
"""

week1 = input("Please write a day of the week: ")
week2 = input("Please write a day of the week: ")
week3 = input("Please write a day of the week: ")

print(week1, week2, week3, sep=",")

"""Create a list containing three lists. The first list should contain the numbers $1$ to $3$, the second should contain the English forms (e.g. "one") of these words. And the last should contain Boolean values which are True if the corresponding number is prime (hint: $1$ is not prime, $2$ and $3$ are)"""

list_oflists = [[1,2,3], 
                ["one", "two", "three"],
                [False, True, True]]

"""Lists of lists don't have to be square. Create a list containing lists of length $1$, $2$, and $3$, each filled with numbers of your choosing"""

list_not = [[1], 
            [1,2],
            [1,2,3]]

"""## Extracting List Elements

Run the following code to generate a list of random numbers with a length randomly chosen between 50 and 100
"""

from random import random, randint, seed
seed(1729)
numbers = [random() for __ in range(randint(50, 100))]

"""What is the 42nd element of this list?"""

numbers[41]

"""What is the value of the element that is tenth from the end of the list?"""

numbers[-10]

"""What happens when you try to access the value of an index that doesn't exist?"""

numbers[100]

"""out of range error appears

_This is quite a tough challenge, but try to persevere. You can always check out the solutions if you're unsure_

The following code will create a reordering of the numbers 0 to 99
"""

from random import shuffle, seed
mapping = [i for i in range(100)]
seed(1729)
shuffle(mapping)
print(mapping)

"""You can think of this as a sort of mapping, where the value of a given index tells you which index to look at next. For example index zero contains the value $26$ so we'd next look at index $26$. This has value $60$ so we'd then look at index $60$, etc.

It is not hard to show that if you continue following this rule, you'll eventually get back to where you started. It would be interesting to know how many steps this takes.

Ask the user for an index to start from and then follow the rule until you get back to the start, keeping track of how many steps this takes.

You will want to define a variable `steps` to keep track of how many steps you've taken as well as a variable `curr_value`, initial set to the starting value, to hold the current value you are looking at. You should keep looping until `curr_value == start_value` and `steps >= 1`. The last condition is needed to ensure that you don't immediately exit the loop. On each loop iteration you can increment the step count and update the current value to be `mapping[curr_value]`. Have a go at tying these ideas together into a solution.
"""

start_value = int (input("Please, write a value for the index: "))
steps = 0
curr_value = start_value
while curr_value != start_value or steps ==0:
  curr_value = mapping[curr_value]
steps = steps + 1
print("Retured to", start_value, "after", steps, "steps")

"""(Fun fact: for a mapping with $n$ elements, the average chain length is roughly equal to $\frac{n}{\log(n)}$)

## Slicing Lists

Using the variable `numbers` from above, extract a sub-list containing the 5th to 15th elements
"""

numbers[4:14]

"""Extract a sub-list containing all of the 5 last elements except the actual last"""

(numbers[-5:-1])

"""If I use the slice `m:n` with $m<n$, how many elements will the resulting list contain?"""

print(numbers[3:4])
print(numbers[2:3])

"""You are welcome to use variables as the indices for your slice.
* Create a list of 10 numbers
* Set a variable `n` to initially be 2
* Loop until `n` is greater than 5, incrementing `n` by one each time
* On each loop print out the results of taking the slice `n:8`
"""

num = [1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 , 10]
n=2
while n <= 5:
  print(num[n:8])
  n+=1

"""## Manipulating Lists

Create an empty list called `squares` using `squares = []`
"""

squares = []

"""Loop through the values 1 to 10, appending the square of this value to the list at each stage. Finish by printing out the variable"""

n=1
while n <=10:
      squares.append(n**2)
      n += 1
print(squares)

"""You can check if a value is in a list using `val in my_list`. Use this idea alongside the method for removing by value to delete all instances of the word "spam" in the following list"""

menu = ["Spam", "Sausage", "Spam", "Spam", "Spam", "Bacon", "Spam", "Tomato", "Spam"]

while "Spam" in menu: 
  menu.remove("Spam")
print(menu)

"""Create a list of decimal numbers and loop through it, replacing each element with half its current value"""

dec = [1.5,2.5,4.5,7.5]
i =0
while i < len(dec):
  dec[i] =dec[i]/2
  i += 1
print(dec)

"""Beware: when you delete an element of a list, you will change its length and cause all elements after it to 'shuffle down'. Create a list of 8 numbers and delete every other element, starting with the first, using a while loop."""

nums = [1 ,2 ,3 ,4 ,5 ,6 ,7 ,8]
n = 0
while n < len(nums):
  del nums[n]
  n+=1
print(nums)

"""## Tuples

Create a tuple containing five numbers. Extract the last value using negative indexing
"""

new_tuple = (1,2,3,4,5)
print(new_tuple[-1])

"""Just like we can convert between data types using `int()`, `str()`, `float()` and `bool()`, we can convert between lists and tuples using `list()` and `tuple()`. Create a list, append a value, convert it to a tuple then attempt to append another value, confirming that this can't be done"""

lists = [2, 4, 6, 8]
lists.append(4)
print(lists)
lists = tuple(lists)
lists.append(6)

"""Repeat this in the opposite direction, starting with a tuple"""

tuplelist = (2, 4, 6, 8)
tuplelist.append(4)
print(tuplelist)
tuplelist =list(tuplelist)
tuplelist.append(6)