# -*- coding: utf-8 -*-
"""session_six_exercises.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/warwickdatascience/beginners-python/blob/master/session_six/session_six_exercises.ipynb

<a href="https://colab.research.google.com/github/warwickdatascience/beginners-python/blob/master/session_six/session_six_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>Spotted a mistake? Report it <a href="https://github.com/warwickdatascience/beginners-python/issues/new">here</a></center>

# Beginner's Python—Session Six Homework Exercises

_As we are moving deeper into the world of Python, the tasks we can complete with our skills can become more and more complicated. For that reason, there are fewer exercises to complete this week but of a slightly harder standard. Don't be put off; these are meant to challenge you._

## Functions

Create a function called `pi` which returns the value `3.14159`
"""

def pi():
  return 3.14159

pi()

"""Create two functions, `circumference` and `area` which each have a single parameter `radius`. These should return the circumference and area of a circle with radius `radius` respectively. (See session one for the formulae for these)"""

def circumference(radius):
  return 2*pi()*radius
def area(radius):
  return pi()*radius**2

print("The circumference of the circle with raduis 2 is ", circumference(4))
print("The area of a circle with raduis 2 is", area(4))

"""Create a function `describe_list` which prints the min, mean, and max of a list."""

num = [1,2,3,4,5]
def describe_list(num):
  return min(num), max(num), sum(num)/len(num)

print("The min, max and mean are",
      describe_list(num), 
      "respectively")

"""Evaluate the following code cell to define the contained function"""

def print_row(r, n):
    w = n - 2 * abs((n - 1) // 2 - r)
    print(( '*'* w).center(n))

"""Create a function, `print_diamond` which has parameter `size`. If `size` is even, print an error message. Otherwise loop through the numbers 0 to `size-1` using the counter variable `row` and call `print_row(row, size)` each iteration"""

def print_diamond(size):
  if size % 2 == 0:
    print("You have an error!")
  else:
    for row in range(0, size):
      print_row(row,size)

print_diamond(7)

"""## Recursion

What happens when we create a function that calls itself with no condition to eventually stop the recursion? Here's an example:
"""

def recurse():
    return recurse()
recurse()

"""There is an error.

Use recursion to create a function `product` which calculates the product of all items in a list. This should take a list as its single argument. There are then two cases. If the list is of length 1, return that number. If the list is of length 2 or more, return the product of the first element and the result of passing the rest of the list to `product()`
"""

example = [3,7, 2, 8]
def product(example):
  n = len(example)
  if n == 1:
    return example[0]
  else:
    return example[0] * product(example[1:])
product(example)

"""The greatest common divisor (GCD) of two integers is the largest integer which divides both of them. Greek mathematician Euclid, is famous for discovering the following recursive definition of the GCD.

$$\textrm{GCD}(a, b) = \textrm{GCD}(b, a \text{ mod } b)$$

Where $\text{mod}$ is the modulus operator given by `%` in Python. We also have that $\textrm{GCD}(a, 0)=a$ for any integer $a$. Use this to write a recursive function to calculate the GCD of two integers.
"""

def gcd(a, b):
    if b == 0:
        return a
    else:
        return gcd(b, a % b)
    
gcd(24, 32)

"""## Variable Scope

Exercises for variable scope don't make much sense, so instead read [this short article](https://matthew-brett.github.io/teaching/global_scope.html) on variable scope to re-cap
"""