# -*- coding: utf-8 -*-
"""session_seven_exercises.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/warwickdatascience/beginners-python/blob/master/session_seven/session_seven_exercises.ipynb

<a href="https://colab.research.google.com/github/warwickdatascience/beginners-python/blob/master/session_seven/session_seven_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>Spotted a mistake? Report it <a href="https://github.com/warwickdatascience/beginners-python/issues/new">here</a></center>

# Beginner's Python—Session Seven Homework Exercises

_As we are moving deeper into the world of Python, the tasks we can complete with our skills can become more and more complicated. For that reason, there are fewer exercises to complete this week but of a slightly harder standard. Don't be put off; these are meant to challenge you._

## Dictionaries

Create a dictionary with two keys, `x` and `y` the value of each being a numeric list of length 5. Notice, that this is essentially a dataframe/table with two variables.
"""

dict1 = { 'x':[1,2,4,5], 
         'y': [2,4,6,8,10]}

"""Ask the user for their name, age, and whether they own a dog. Assign the responses to variables `name`, `age`, and `has_dog`. Remember to convert the inputted age to an integer. The response for the last question should be either `yes` or `no` which should then be converted to `True` or `False` respectively. You can use the example from near the end of the session three presentation as a basis for this."""

name = input("What is your name? " )
age = int (input("How old are you? "))
has_dog = ''
while not has_dog in ('yes', 'no'):
    has_dog = input("Do you have a dog? ")
has_dog = has_dog == 'yes'

"""Create a dictionary containing the users information using the three variables defined above. Print out these values in a meaningful sentence using this dictionary."""

user = {'name': name, 'age': age, 'has_dog': has_dog}
if user['has_dog']:
    dog_text = "do"
else:
    dog_text = "do not"
print("Hi, I'm", user['name'] + ".",
      "I am", user['age'], "and I",
      dog_text, "have a dog.")

"""Dictionary keys are not limited to strings although there are limits. Try to create dictionaries with keys of type integer, float, Boolean, list, tuple, and dictionary, respectively. Which are allowed and what error do you recieve when a key's type is invalid?"""

int_dict = {1: 1}

float_dict = {1.0: 1}

boolean_dict = {True: 1}

tuple_dict = {(1,1): 1}

list_dict = {[1,1]: 1}

dict_dict = {{1,1}: 1}

"""Dictionaries are also advantagous over lists when storing _sparse_ data (data with lots of missing or default values).

Suppose there is a race with one thousand participants. We know that the first place was awarded to 'Ann' and last place to 'Bob'. Create an 1000 element list (by starting from an empty list and appending) to store this information using the string 'Unknown' for any race position for which we don't know the winner.
"""

place_names = []
for i in range(1000):
    if i == 0:
        place_names.append('Ann')
    elif i == 999:
        place_names.append('Bob')
    else:
        place_names.append('Unknown')

"""Store this information in a two item dictionary and create a function `get_name(i)` to access the name of the person in the ith place. Remember, you can use `in` to check for the existance of a key in a dictionary."""

place_dict = {1: 'Ann', 1000: 'Bob'}

def get_name(i):
    if i in place_dict:
        return place_dict[i]
    else:
        return 'Unknown'
    
print(get_name(1))
print(get_name(2))

"""Consider the amount of storage required for each solution—there should be a clear winner!

## Manipulating Dictionaries

The following code creates a list of the letters of the English alphabet (called `letters`)
"""

from string import ascii_uppercase
letters = list(ascii_uppercase)

"""Create an empty dictionary called `encode` and loop through the list using enumeration to add key-value pairs to the dictionary mapping each letter to its position in the alphabet (`A -> 1, B -> 2, ..., Z -> 26`)"""

encode = {}
for i, n, in enumerate(letters):
  encode[n]= i+1
print(encode)

"""Loop through the list of letters (without enumeration this time) to decrease the value of each key by one so that the new mapping is (`A -> 0, ..., Z -> 25`)"""

for l in letters:
    encode[l] = encode[l] - 1
print(encode)

"""Given an uppercase string, loop through its letters and use this dictionary to encode the text into a numeric list. For example the word 'BAG' would be encoded as `[1, 0, 6]`."""

word = input("Please write a word in caps. ")
encoded = []
for i in word:
   encoded.append(encode[i])
print(encoded)

"""Create a function that when given a dictionary and a key will delete the item associated with that key only if the key exists"""

test_dict = {'A': 1, 'B': 2}

def delete_dict(dictionary, key):
  if key in dictionary:
    del dictionary[key]
  
delete_dict(test_dict, 'A')
delete_dict(test_dict, 'C')
print(test_dict)

"""## Looping Through Dictionaries

As promised, we will look at removing a key by value. We can do this by looping through the items of a dictionary and deleting a corresponding key if the value matches. Use this to remove all instances with the value `Homer` in the following dictionary
"""

father = {
    'Bart': 'Homer',
    'Homer': 'Abe',
    'Lisa': 'Homer'
}

for i, n in list(father.items()):
  if n== 'Homer':
    del father[i]
print(father)

"""How could modify the above code to only delete the first matching instance, as is the case with `.delete()` for lists?

Create an empty dictionary called `decode`. Take the letter mapping dictionary from above and loop through its items and using them to fill `decode` with keys and values reversed
"""

decode = {}
for i, n in encode.items():
  decode[n]=i
print(decode)

"""Take the encoded string from above and decode it by looping through the list and using this dictionary. You will want to use `''.join(list_of_characters)` to combine the decoded letters back into one string. This is the key step in a large amount of machine learning with text data and cryptography"""

decoded = []
for number in encoded:
    decoded.append(decode[number])
decoded = ''.join(decoded)
print(decoded)